server:
  port: 8082
spring:
  application:
    name: tracker

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.oswe.tracker.dto"
        spring.json.value.default.type: "com.oswe.tracker.dto.OrderCreatedEvent"
        spring.json.use.type.headers: false

    #se agrega un producer ya que al realizar los reintentos, debo de actuar como un producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
tracker:
  kafka:
    orders-topic: orders
